server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: GAOFAN.19940430
    url: jdbc:mysql://193.112.88.125:3306/demo?characterEncoding=utf8
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    enabled: true
